spring:
  profiles:
    active: dev
    include: secret, db, data
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always