spring:
  profiles:
    active: dev
    include: secret, data
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: 172.17.0.1