spring:
  thymeleaf:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${redis.devHost}
  kafka:
    bootstrap-servers: localhost:${custom.kafka.devPort}

custom:
  redis:
    host: ${redis.devHost}
kafka:
  host: "localhost:"
  port: ${custom.kafka.port}