spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${dev.dataSource.kind}://${dev.dataSource.host}:${dev.dataSource.port}/${dev.dataSource.db}
    username: ${dev.dataSource.username}
    password: ${dev.dataSource.password}
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${dev.redis.host}
  kafka:
      bootstrap-servers: ${dev.kafka.host}:${dev.kafka.port}

logging.level:
  org:
    hibernate.SQL: error

kafka:
  host: ${dev.kafka.host}
  port: ${dev.kafka.port}
redis:
  host: ${dev.redis.host}
  port: ${dev.redis.port}