spring:
  thymeleaf:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${test.redis.host}

redis:
  host: ${test.redis.host}
  port: ${test.redis.port}