tag:
  오버핏청바지, 시티보이룩, 스포티캐주얼, 빈티지룩, 프레피스타일,
  모던미니멀리스트, 로맨틱룩, 로커룩, 힙합룩, 데님스타일,
  스트릿패션, 빅사이즈룩, 오가닉패션, 애슬레저룩, 비즈니스캐주얼,
  테일러드룩, 코지니트, 밀리터리룩, 고딕패션, 펑크룩,
  레트로스타일, 베이직룩, 컬러풀패션, 모노톤스타일, 럭셔리룩,
  블랙스타일, 루즈핏패션, 크롭트스타일, 블레이저룩, 코디로이패션

main-category:
  추천, 상의, 아우터, 하의, 신발, 가방, 악세서리

top:
  반소매티셔츠, 긴소매티셔츠, 피케/카라 티셔츠, 셔츠/블라우스, 니트/스웨터, 후드티셔츠, 맨투맨/스웨트셔츠
outer:
  후드집업, 라이더자켓, 블루종, 싱글코드, 더블코드, 롱패딩, 숏패딩, 카디건, 플리스, 코치자켓, 기타아우터
bottom:
  데님팬츠, 숏팬츠, 코튼팬츠, 레깅스, 슬랙스, 트레이닝팬츠, 기타바지
shoes:
  구두, 샌들, 로퍼, 슬리퍼, 힐, 플랫슈즈, 부츠, 블로퍼
bag:
  백팩, 웨이스트백, 메신저백, 캐리어, 숄더백, 토트백, 에코백, 더플백, 클러치백
accessory:
  벨트, 장갑, 스카프, 키링, 넥타이, 머플러, 기타악세서리


brand:
  아디다스, 나이키, 버버리, 라퍼퍼