server:
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${custom.dataSource.kind}://${custom.dataSource.host}:${custom.dataSource.port}/${custom.dataSource.db}
    username: ${custom.dataSource.username}
    password: ${custom.dataSource.password}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
  kafka:
    bootstrap-servers: ${custom.kafka.host}:${custom.kafka.port}

custom:
  redis:
    host: ${redis.host}
kafka:
  host: "my-cluster-kafka-bootstrap"
  port: ${custom.kafka.port}