spring:
  profiles:
    active: dev
    include: secret, db, data, ela
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: my-cluster-kafka-external-bootstrap:9094