server:
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${prod.dataSource.kind}://${prod.dataSource.host}:${prod.dataSource.port}/${prod.dataSource.db}
    username: ${prod.dataSource.username}
    password: ${prod.dataSource.password}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
redis:
  host: ${prod.redis.host}
  port: ${prod.redis.port}