spring:
  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: 172.17.0.1
logging.level:
  org:
    hibernate.SQL: debug

